name: Build and Release Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.4"

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    # Windows 构建
    - name: Build Windows Executable
      if: matrix.os == 'windows-latest'
      run: pyinstaller --onefile -n 七猫小说下载器 -i favicon.ico main.py
      shell: cmd
      env:
        PATH: ${{ env.Path }};C:\Python312

    # macOS/Linux 构建
    - name: Build Unix Executable
      if: matrix.os != 'windows-latest'
      run: pyinstaller --onefile -n 七猫小说下载器 main.py
      shell: bash

    - name: Upload All Dist Files
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: release_package/

    - name: Debug Release Files
      run: |
        echo "=== 下载后的文件列表 ==="
        ls -lh release_package/
        echo "=== 文件树结构 ==="
        tree release_package/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: 七猫小说下载器 v${{ github.event.inputs.version }}
        body: |
          ### 发布说明
          自动构建版本包含以下特性：
          - 跨平台兼容性优化
          - 依赖库版本更新
          - 自动签名验证
        draft: false
        prerelease: false
        files: release_package/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
