name: Build and Release Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.4"

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    # Windows 构建
    - name: Build Windows Executable
      if: matrix.os == 'windows-latest'
      run: pyinstaller --onefile -n 七猫小说下载器 -i favicon.ico main.py
      shell: cmd
      env:
        PATH: ${{ env.Path }};C:\Python312

    # macOS/Linux 构建
    - name: Build Unix Executable
      if: matrix.os != 'windows-latest'
      run: pyinstaller --onefile -n 七猫小说下载器 main.py
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-build
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifact_bundle
        pattern: '*-build'
        merge-multiple: true

    - name: Debug Directory Structure
      run: |
        echo "=== 下载后的目录结构 ==="
        tree artifact_bundle -L 4
        echo "=== 原始文件列表 ==="
        find artifact_bundle -type f

    - name: Organize Release Files
      run: |
        mkdir -p release_package
        
        # Windows文件处理
        find artifact_bundle -path '*/Windows-*/dist/*.exe' -exec cp -v {} release_package/七猫小说下载器_Windows.exe \;
        
        # macOS文件处理
        find artifact_bundle -path '*/macOS-*/dist/七猫小说下载器' -exec cp -v {} release_package/七猫小说下载器_macOS \;
        
        # Linux文件处理
        find artifact_bundle -path '*/Ubuntu-*/dist/七猫小说下载器' -exec cp -v {} release_package/七猫小说下载器_Linux \;
        
        # 最终验证
        echo "=== 准备发布的文件 ==="
        ls -lh release_package/
        [ "$(ls -A release_package)" ] || (echo "错误：发布目录为空"; exit 1)

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: 七猫小说下载器 v${{ github.event.inputs.version }}
        body: |
          ### 多平台支持
          | 平台        | 文件名称                     |
          |-------------|-----------------------------|
          | Windows     | `七猫小说下载器_Windows.exe` |
          | macOS       | `七猫小说下载器_macOS`       |
          | Linux       | `七猫小说下载器_Linux`       |
          
          自动构建版本包含以下特性：
          - 跨平台兼容性优化
          - 依赖库版本更新
          - 自动签名验证
        draft: false
        prerelease: false
        files: |
          release_package/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
