name: Build and Release Python Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.4

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    # 各平台独立构建步骤
    - name: Build Windows Executable
      if: matrix.os == 'windows-latest'
      run: pyinstaller --onefile -n 七猫小说下载器windows -i favicon.ico main.py
      shell: cmd  # 显式指定CMD shell

    - name: Build macOS Executable
      if: matrix.os == 'macos-latest'
      run: pyinstaller --onefile -n 七猫小说下载器MacOS main.py
      shell: bash

    - name: Build Linux Executable
      if: matrix.os == 'ubuntu-latest'
      run: pyinstaller --onefile -n 七猫小说下载器Linux main.py
      shell: bash

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare Release Files
      run: |
        mkdir -p release_files
        find artifacts -name '*.exe' -exec mv {} release_files/ \;
        find artifacts -name '七猫小说下载器*' ! -name '*.exe' -exec mv {} release_files/ \;

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        body: |
          多平台可执行文件版本：
          - Windows: 七猫小说下载器windows.exe
          - macOS: 七猫小说下载器MacOS
          - Linux: 七猫小说下载器Linux
        files: |
          release_files/*
